import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { AuthProvider } from "@/authContext";
import { CartProvider } from "../cartContext";
import { SearchProvider } from "@/searchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FakeCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="fantasy" lang="en">
      <AuthProvider>
        <SearchProvider>
          <CartProvider>
            <body className={inter.className}>
              <Navbar />
              {children}
              <Footer />
            </body>
          </CartProvider>
        </SearchProvider>
      </AuthProvider>
    </html>
  );
}
